### ISSUE TITLE
Is there an equivalent to v4's static `hide` method?

### ISSUE THREAD

**Issue by ericpatey** [ReactTooltip/react-tooltip#1034]
We would like to upgrade to v5, but we have a couple of use cases where we imperatively hide all tooltips. We would do this by calling the static `hide` method with no parameter.

**Comment by gabrieljablonski** [comment]
Since v5 dropped the idea of a "global" tooltip, there's no direct way to hide all of the tooltips. Here's a few suggestions on how to achieve the same effect.

If you're trying to hide tooltips from a place in your application fairly close to where the tooltips and/or anchors are placed, you can use the new `hide` tooltip prop, and/or the `data-tooltip-hidden` anchor attribute, and control the hidden state with standard prop drilling/bubbling.

If your application is fairly wide/deep (which would make prop drilling rather cumbersome), I suggest doing the same as suggested above, but using a context provider instead to control the hidden state.

**Comment by ericpatey** [comment]
Wow. Thanks for the quick response. I just wanted to make sure I wasn't missing anything. That's exactly the guidance I was looking for.
