### ISSUE TITLE
[FEAT REQ] setClose or close method

### ISSUE THREAD

**Issue by sovetski** [ReactTooltip/react-tooltip#1036]
**Is your feature request related to a problem? Please describe.**
I know that there is an option to make the tooltip "hidden", but it does not help in my case, once we set "hidden" to "true", it does not appear anymore. In some situation, we need to manage the hide/show manually, for example I am using this package: https://github.com/JedWatson/react-select and I need to manage it on my side, if not Tooltip will not work.

**Describe the solution you'd like**
What will be perfect, is to get a method like "close()" to be able to close the tooltip which will show again if we hover on the parent element. I saw that there is already a function named "handleShow", maybe you can just "export" it?

**Describe alternatives you've considered**

**Additional context**
If you make "handleShow" public, it should be fine, if not, adding "close()" and "show()" will be very useful.

**Comment by gabrieljablonski** [comment]
The easiest way to expose a function such as `handleShow()` would require using a context provider, which is something we're trying to move away from.

The other alternative is exposing a `ref` prop which we could use to expose this and possible other functions with `useImperativeHandle()`.

We're not planning on working on this right now, since it seems like a more unusual (although very valid) use-case, though I'll leave this open since it's still an interesting idea that we can work on in the future.

---

My suggestions for a workaround:

1. Fully control the `isOpen` prop manually if you need some complex use-cases. [Some examples from the docs.](https://react-tooltip.com/docs/examples/state)
2. If what you need is simple enough, you could do something like in [this example](https://stackblitz.com/edit/stackblitz-starters-kaudc6?file=src%2FApp.tsx). If you have multiple tooltips, you can write a wrapper component with your custom logic.

```tsx
import * as React from 'react';
import { Tooltip } from 'react-tooltip';

export default function App() {
  const [hidden, setHidden] = React.useState(false);

  return (
    <div>
      <button
        data-tooltip-id="my-tooltip"
        data-tooltip-content="Hello World!"
        // can be used instead of `hidden` prop
        // data-tooltip-hidden={hidden}
        onClick={() => setHidden(true)}
        onMouseLeave={() => setHidden(false)}
      >
        click me!
      </button>
      <Tooltip id="my-tooltip" hidden={hidden} />
    </div>
  );
}
```

**Comment by r3wt** [comment]
> **We're not planning on working on this right now, since it seems like a more unusual (although very valid) use-case**

why on earth should people not wanting to use controlled state for tooltips in the year 2023 be an "unusual" use case. its a significant factor that lead me to choose your library to begin with. that, along with single anchor element, and html content support were my reasons for choosing your lib. the notion that exporting a close function from your package is some forbidden anti pattern is ridiculous. i beg you to reconsider this.

**Comment by gabrieljablonski** [comment]
> the notion that exporting a close function from your package is some forbidden anti pattern is ridiculous

At no point I said this would be a "forbidden antipattern". If so, this issue would've been closed long ago as "not planned".

This is not as trivial as "exporting a close function" (trust me, I've tried). Due to internal design, it would require a few intricate changes for this feature to work without bugs.

> why on earth should people not wanting to use controlled state for tooltips in the year 2023 be an "unusual" use case

In my experience in maintaining this package for almost a year, most (I'd easily say 90%+) of use-cases I've seen involve using the tooltip (at least functionally) with mostly default options. Most people just need a quick and easy way to show stuff when hovering an element, and that's about it. Rarely have we had to suggest workarounds (such as in my comment above) to features not yet available.

We appreciate your input, and we *will* implement this (again, the issue would've been already closed otherwise). But unfortunately, this would take a bit more time than we have available to dedicate to this project right now.

**Comment by r3wt** [comment]
@sovetski did you find a work around, if not, i will share my somewhat poor solution here.

```tsx
const useActiveElement = () => {
  const [active, setActive] = useState(document.activeElement);
  
  const handleFocus = () => {
    setActive(document.activeElement);
  }
  
  useEffect(() => {
    document.addEventListener('focusin', handleFocus)
    document.addEventListener('focusout',handleFocus)
    return () => {
      document.removeEventListener('focusin', handleFocus);
      document.removeEventListener('focusout', handleFocus);
    };
  }, [])
  
  return active;
}
```

**Comment by gabrieljablonski** [comment]
@sovetski It's been quite a while, but if you'd like to try out the beta version `react-tooltip@5.22.0-beta.1109.0`, we now expose `open()` and `close()` methods (and some more).

Still doing some testing and no documentation yet, but it should be merged soon.

See the [changes on the PR](https://github.com/ReactTooltip/react-tooltip/pull/1109/files) for some info on how to use it, but you just need to create the ref and use it.

```tsx
const tooltipRef = React.useRef<TooltipImperativeProps>(null)

tooltipRef.current?.open()
tooltipRef.current?.close()

<Tooltip ref={tooltipRef} />
```
```tsx
interface TooltipImperativeOpenOptions {
  anchorSelect?: string
  position?: IPosition
  content?: ChildrenType
}

interface TooltipImperativeProps {
  open: (options?: TooltipImperativeOpenOptions) => void
  close: () => void
  /**
   * @readonly
   */
  activeAnchor: HTMLElement | null
  /**
   * @readonly
   */
  place: PlacesType
  /**
   * @readonly
   */
  isOpen: boolean
}
```

**Comment by gabrieljablonski** [comment]
After quite some time, `react-tooltip@5.23.0` implements this feature.

@sovetski thanks for the original suggestion, and feel free to make many more!
