### ISSUE TITLE
Avoiding `!important` is not always possible; the docs should reflect that.

### ISSUE THREAD

**Issue by shepmaster** [ReactTooltip/react-tooltip#1066]
The docs say:

> You don't need to use `!important` to override the styles, take advantage of CSS Specificity instead

However, this doesn't always work. I'd recommend that the phrasing be softened a bit — something like "you don't need it most of the time". Going into more detail or linking somewhere would also be wonderful, of course. 

### Details

[Code Sandbox](https://codesandbox.io/s/serene-goldberg-fg5m83) example.

Specifically, I am attempting to set the maximum width of a tooltip. This is the `class` attribute of the tooltip (split on spaces to make it easier to read):

```
react-tooltip
react-tooltip__tooltip_KtSkBq
react-tooltip__dark_KtSkBq
my-awesome-class
react-tooltip__place-bottom
react-tooltip__show_KtSkBq
```

In practice, the `width: max-content;` from `.react-tooltip__tooltip_KtSkBq` **supersedes** the `width: 100em;` from `.my-awesome-class`. I believe that's because both of those have the same specificity but React-Tooltip's CSS is appended to the `<head>` element, coming later in the document. That means that "the proximity rule comes into play, wherein the last declared style gets precedence".

```html
<style type="text/css">/* my styles */</style>
<style id="/node_modules/react-tooltip/dist/react-tooltip.css:-css" type="text/css">/* react-tooltip styles */</style>
```

Our app is one of those that has grown and morphed over time, adding React later in its life. It's a Rails app that uses Sass to generate the CSS. Rails generates the HTML skeleton and adds the `<style>` before React even boots. Only later will React-Tooltip's style be loaded.

I don't think there's any bug *per se*, I just got excited that we could remove the `!important` from our app when upgrading from v4 to v5 and it took some time to realize my mistake.

**Comment by gabrieljablonski** [comment]
Here's an example using v5.18.1.

https://codesandbox.io/s/flamboyant-snow-p5wjmj?file=/src/styles.css

If possible, try upgrading (also remove the CSS import statement for `react-tooltip.css`, the styles are automatically injected since v5.13.0.

I've tried for a few minutes to get an example where I'd have to adjust the CSS specificity (or forcibly use `!important`), but couldn't find one. If you're able to provide a reproducible case, please do.

---

Furthermore, I personally believe the documention goes quite in-depth into how you would properly use the CSS specificity. 
The best I can see is changing the text you've quoted to something like:

> You don't need to use `!important` to override the styles, take advantage of CSS Specificity instead, **as detailed further on.**

**Comment by shepmaster** [comment]
> Here's an example

Yes, and this has moved my CSS from the `<head>` element in`index.html` to `src/styles.css`, which is exactly my point: our application can not do that, at least not trivially.

> If you're able to provide a reproducible case

I did, but then it was changed to be structurally different 😉. However, `my-awesome-class` is still inside `index.html`, so just... delete it from `src/styles.css` in the updated example. Then the library's injected styles will have the same specificity as the application's styles (0 id, 1 class, 0 type) but they will occur **later** than the application styles and take precedence:

![image](https://github.com/ReactTooltip/react-tooltip/assets/174509/b50fddc7-0714-40cc-bb25-01c10ebb5a30)





> using v5.18.1 [...] try upgrading [...] remove the CSS import statement

I started from the [example provided in the README](https://github.com/ReactTooltip/react-tooltip/blob/01305c7c847695f9b67ee711743631323639d369/README.md#L31). If the recommended usage has changed, you may wish to update that source.

**Comment by gabrieljablonski** [comment]
> Rails generates the HTML skeleton and adds the <style> before React even boots. Only later will React-Tooltip's style be loaded.

I completely ignore this part when reading your issue, my bad.

I'll re-evaluate this and let you know.

**Comment by gabrieljablonski** [comment]
> I started from the [example provided in the README](https://github.com/ReactTooltip/react-tooltip/blob/01305c7c847695f9b67ee711743631323639d369/README.md#L31). If the recommended usage has changed, you may wish to update that source.

Regarding importing the `react-tooltip.css` file, the current README clearly states:

> This needs to be done only once and only if you are using a version before than 5.13.0. We suggest you do it on your src/index.js or equivalent file.

I've mentioned upgrading and removing the import statement because your original codesandbox is using v5.10.1.

---

Now that I've actually payed attention to the problem you've described, I believe this example solves your issue.

https://codesandbox.io/s/clever-dawn-g55s4m?file=/public/index.html

Relevant snippet:

```css
.app-container > .my-awesome-class {
  width: 10em; /* !important; */
}
```

To accomplish what you're trying to do, as the docs suggest, you must **increase CSS specificity**. As we could come up with literally hundreds of ways to increase the specificity, the easiest suggestion I can give is referring to the tooltip parent on your CSS selector, as seen above.

As I've said, I believe the docs are quite clear on how to achieve this (detailed on [this section](https://react-tooltip.com/docs/examples/styling#classes)). If you don't agree with that, please let us know if there's anything missing, or information that could be better presented about this.
