### ISSUE TITLE
Release notes potentially missing breaking change

### ISSUE THREAD

**Issue by mpenndev** [ReactTooltip/react-tooltip#1088]
Hi All,

Upgrading the package from v5.18.1 to v5.19.0 onwards (tested v5.21.3) causes our styling to be overridden.

Thought it might be worth updating the release notes to warn users if this is known / can be recreated.

Our styles are applied using styled-components:
```
import styled from 'styled-components'
import { Tooltip } from 'react-tooltip'

const StyledTooltip = styled(Tooltip)`
    background-color: ${props => props.theme.colors.primary};
    color: ${props => props.theme.colors.textOnPrimary};
    border-radius: 10px;
    opacity: 1;
    box-shadow: rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;
`

export default StyledTooltip
```

In v5.18.1 these are applied as expected in the class `.iPBbxu`:
![Screenshot 2023-09-07 111055](https://github.com/ReactTooltip/react-tooltip/assets/11893741/caf1967c-8c51-45bc-be06-b82e78dc1d62)

After updating the built-in styles are more specific and override the styled-components class:
![Screenshot 2023-09-07 111230](https://github.com/ReactTooltip/react-tooltip/assets/11893741/6e12f11d-de26-4eec-8944-111ba89d0485)

P.S. Thanks for all the hard work!

**Comment by gabrieljablonski** [comment]
Please try using `<StyledTooltip disableStyleInjection={true} />`. You can read more about it [here](https://react-tooltip.com/docs/examples/styling#disabling-reacttooltip-css).

If that works, we'll update the release notes for the relevant version.

**Comment by mpenndev** [comment]
Disabling the base styles stops the override on _most_ of the properties:
![image](https://github.com/ReactTooltip/react-tooltip/assets/11893741/d11690ff-ecb4-4050-9907-c1f91cf711ad)

Just to make the difference a bit easier to see;
Before (v5.18.1):
![image](https://github.com/ReactTooltip/react-tooltip/assets/11893741/23617ca3-a1ec-4354-8723-05120be9ddd4)

After (v5.21.3):
![image](https://github.com/ReactTooltip/react-tooltip/assets/11893741/9ef84155-f8ed-4e51-9adf-40e24930b459)

After with `disableStyleInjection={true}`:
![image](https://github.com/ReactTooltip/react-tooltip/assets/11893741/08b10bed-19d1-41bf-9c6d-14e9e29970ae)

**Comment by gabrieljablonski** [comment]
Overriding the opacity through CSS styling is not supported. Use the `opacity` tooltip prop instead.

**Comment by gabrieljablonski** [comment]
As for the other styling changes, check out the [styling examples](https://react-tooltip.com/docs/examples/styling).

If you do not wish to have to set all of the other styling attributes manually, consider using CSS specificity instead of `disableStyleInjection`.

**Comment by gabrieljablonski** [comment]
Missed some details to make my answer clearer, I should probably stop answering issues too early in the morning 😅

Since v5.18.1 (there was also another change a couple versions earlier than that), we changed how the tooltip handles styling.

Since then, you have basically two options for styling the tooltip.

1. Change a few attributes using CSS classes just as you were doing originally, but also taking consideration CSS specificity so the styles are actually applied ([see docs](https://react-tooltip.com/docs/examples/styling))

2. Use `disableStyleInjection` and style the tooltip from scratch. As you've noticed, this means you'll have to re-add some CSS attributes you do not wish to change. Starting by copying the original [base styles](https://react-tooltip.com/docs/examples/styling#base-styles) and changing what you need is a good way to do it.

In your case I'd actually recommend doing 1, so have a look at our examples for how to use CSS specificity and you should be good to go.

**Comment by gabrieljablonski** [comment]
Closing for now. Let us know if there's anything else.
