### ISSUE TITLE
how to make tooltip initially open with uncontrolled state

### ISSUE THREAD

**Issue by alondon17** [ReactTooltip/react-tooltip#1098]
If this is a bug or a Feature request reported using this template, we will close this issue, for those, please use the correct template.

This will be handled as a Question.

your docs are half usable, so many props that don't exist are listed there, we have need a system for menu tooltips  to be loaded when their trigger is clicked for performance reasons. is there a prop for thatbecause setting isOpen to true disables things like the tooltip disappearing after click outside and after scroll

**Comment by gabrieljablonski** [comment]
Hi @alondon17.

**All** of the props for the v5 have a description listed on our [docs page here](https://react-tooltip.com/docs/options), and we also have examples for a bunch of the most useful ones [here](https://react-tooltip.com/docs/category/examples).

You might be looking at the legacy v4 docs, which we have listed since it still used by a lot of people (more than v5 even).

----

> we have need a system for menu tooltips to be loaded when their trigger is clicked

Try using [`openOnClick`](https://react-tooltip.com/docs/options#:~:text=tooltip%20prop%20instead-,openOnClick,-boolean).

**Comment by alondon17** [comment]
i know about that prop, i meant we would like having an option for an initial state, while being uncontrolled, currently we had to replicate the click outside ourselves because the built in doesn't work with isOpen true

**Comment by gabrieljablonski** [comment]
I'll close the issue for now, but let us know if there's anything else.
