### ISSUE TITLE
[BUG]  #1042 Regression from 5.26.0 → 5.26.1

### ISSUE THREAD

**Issue by knubie** [ReactTooltip/react-tooltip#1182]
**Bug description**
See #1042

**Version of Package**
v~5.26.1

**Comment by gabrieljablonski** [comment]
Cannot reproduce the exact issue from #1042 with v5.26.1 (or latest v5.26.3).

https://github.com/ReactTooltip/react-tooltip/assets/21102974/93274294-62d8-4175-bd4c-01f25ac4a365

Using your old repo https://github.com/knubie/react-tooltip-demo (had to remove the CSS definitions from `App.css` copied from the internal tooltip definitions, since we've changed stuff a bit since v5.14.0)

Can you provide some more info on this?

**Comment by gabrieljablonski** [comment]
Not sure why I was unable to reproduce it when this issue was first opened, but after testing it out again for #1204, I managed to reproduce it here https://stackblitz.com/edit/vitejs-vite-bbqqcx?file=src%2FApp.tsx

Working on a fix.

**Comment by gabrieljablonski** [comment]
v5.26.1 introduced a change that was affected by us not correctly resetting the timeout refs in the original fix to this issue.

This beta release should fix it (again) `react-tooltip@5.27.0-beta.1205.rc.0`

Check #1205 for more info.

Will close this as soon as we release an official version with the fix.
