### ISSUE TITLE
On Scroll tooltip is offset by 2x the vertical distance

### ISSUE THREAD

**Issue by simonconway1979** [ReactTooltip/react-tooltip#355]
I am using react-tooltip and seem to get exactly the same issue as: https://github.com/wwayne/react-tooltip/issues/308

When I scroll my tooltip is scrolled 2 X the vertical offset. 

Here is a demo from issue #308 which demonstrates exactly how the issue looks in my app:
http://i.imgur.com/XnuYycj.gifv

I've tried to go through the code and I cannot see where the issue occurs. The left and top position that are set in the updatePosition() seem to give the correct location of the tooltip. 

After looking at issue #147 I tried setting the countTransform attirbute to false but this didn't have any effect. (I thought it might be related because the tooltip sits inside component that uses transform.)

Any ideas would be much appreciated.

**Comment by kailaskore** [comment]
+1

**Comment by aronhelser** [comment]
If anyone can provide demo code that can be debugged, that would help - or if you can use clues from #147 to isolate the problem, I'm happy to merge a PR 😄

**Comment by conor-kelleher** [comment]
The issue can be recreated by putting the tooltip inside an element with a scroll. The issue doesn't show when the entire page scrolls but rather just the element containing the tooltip. It moves with the view it is inside but moves too much, presumably something to do with all of the offset calculations in https://github.com/wwayne/react-tooltip/blob/master/src/utils/getPosition.js

**Comment by henryson** [comment]
Great explanation, thanks! 




I did not have time to produce any demo code, I hope this will suffice. 




Regards Josef 







On Fri, May 18, 2018 at 3:45 PM +0200, "Conor Kelleher" <notifications@github.com> wrote:












The issue can be recreated by putting the tooltip inside an element with a scroll. The issue doesn't show when the entire page scrolls but rather just the element containing the tooltip. It moves with the view it is inside but moves too much, presumably something to do with all of the offset calculations in https://github.com/wwayne/react-tooltip/blob/master/src/utils/getPosition.js

**Comment by conor-kelleher** [comment]
I found the answer to my case. I wasn't able to reproduce the issue with your sample project so I concluded that it was because my scrolling element was within a Modal.

I had the <Tooltip /> and the data-tip <div /> both inside the modal so the tooltip element was moving with the scroll (presumably what caused it to mess up).

I fixed it by moving the tooltip outside of the modal and giving it the appropriate data through the `data-tip` prop. Also to get it to render correctly, I had to call `ReactTooltip.rebuild()` inside the modal, as the README.md explains.
