### ISSUE TITLE
How can I render react component within tooltip?

### ISSUE THREAD

**Issue by kopax** [ReactTooltip/react-tooltip#467]
Hi and thanks for sharing this library.

I've been testing a few and it is the only one that work.

One thing I need to do is to passe react-component within the tooltip, but the `data-tip` is the only `prop` I know that can be added in the `tooltip` and it expect a `string`.

Is it possible to render react-component within tooltips?

Thanks in advance

**Comment by kopax** [comment]
Great, may I leave this open as this should be in the documentation?

**Comment by dmc1985** [comment]
That's fine with me.

**Comment by aronhelser** [comment]
It would be great if you wanted to submit a PR with an update to the
examples! Let me know if you think you can....

**Comment by dmc1985** [comment]
@aronhelser I'd be happy to make a PR with an update to the examples. I won't have time for a little while, but I'll do it asap. If I have any trouble, I'll let you know.

@kopax Small thing: I found it's better to use a <span> instead of a <div> in the jsx inside the Tooltip component. Using a <span> controls the position more accurately. 
So my Tooltip component now looks like this: 
```
function Tooltip(props) {

    const tooltipId =  `${props.content || ''}${props.title || ''}${props.theme || ''}${props.place || ''}`
    return (
        <div>
            <ReactTooltip
                id={tooltipId}
                type={props.theme}
                effect='solid'
                place={props.place}
            >
                {props.title && <p className="title">{props.title}</p>}
                <p className='content'>{props.content}</p>
            </ReactTooltip>
            <span data-tip data-for={tooltipId}>
                {props.children}
            </span>
        </div>
    );
}
```

Also, when implementing the tooltip in your app, try to wrap it in the smallest div possible to control its position. So for example. Instead of doing `<h2><Tooltip>Text</Tooltip></h2>`, 
I found this works better:
`<h2><Tooltip><span>Text</span></Tooltip></h2>`

**Comment by Rogger794** [comment]
Hi @dmc1985, any progress in your PR?

**Comment by dmc1985** [comment]
> Hi @dmc1985, any progress in your PR?

Thanks for following up on this and my apologies for the delay. I still would like to do a PR to update the doc with the code snippet, and my goal is to do it over the weekend.

**Comment by dmc1985** [comment]
@Rogger794 @aronhelser When I enter the command `make dev` per the instructions in `contributing.md` I receive the following error: `make: *** No rule to make target `dev'.  Stop.` When I try to launch the server using `yarn start`, I cannot find the correct port to access the development server. What do you recommend I do?

**Comment by Rogger794** [comment]
Hi @dmc1985, could you please bring the last changes from master, I already update the contributing readme.
