### ISSUE TITLE
Trigger tooltip from outside/global

### ISSUE THREAD

**Issue by tonystaark** [ReactTooltip/react-tooltip#503]
In my project, I have several elements that will show tooltip when hover over using react-tooltip.
I am also working on creating an input field such that after I type in the relevant item into the input field, it will trigger the tooltip from the particular element without hovering on that element specifically
I have gone through the documentation and have not seen something that is workable.
Or did I miss it?

**Comment by aronhelser** [comment]
You can use the .Show() and .Hide() methods to trigger the tooltip externally. I don't think we have anything on our example page - it would be a great addition.

**Comment by mhlmhl** [comment]
I have the same requirement.  What I really want is a "show" attribute on <ReactTooltip> that I can set to "true" or "false" as needed.

I have a textarea with the data-tooltip and data-for attributes and an "onKeyDown" event handler.  I have tried calling ".Show()" in the onKeyDown handler but it doesn't work, perhaps because the <ReactTooltip> is not yet rendered....?

Maybe I need to call ".Show()" from a componentDidUpdate() method?

**Comment by mhlmhl** [comment]
Doing the .Show() from a componentDidUpdate method works.  Apparently there is an undocumented interaction between the React lifecycle and the .Show() method.
