### ISSUE TITLE
Warning: Expected server HTML to contain a matching <style> in <div>

### ISSUE THREAD

**Issue by oran1248** [ReactTooltip/react-tooltip#601]
Hi,

I'm using next.js and SSR.

I'm rendering ReactTooltip comp only on client side with the following code:
```
    let tooltipComp = null;
    if (isRunningOnClient()) {
        tooltipComp = <ReactTooltip />
    }
```

But only on dev mode i'm getting this warning:
`Warning: Expected server HTML to contain a matching <style> in <div>.`

What is the cause and the solution? thanks

**Comment by divmgl** [comment]
After dealing with this myself and reading through the source code, there is no actual way of achieving this currently. This is because of the way `Wrapper` is implemented. It's using `dangerouslySetInnerHtml`, which causes the client to expect to receive a `div` from the server. 

One of the easiest ways to overcome this is to allow `Wrapper` to be any kind of `node`. Unfortunately, this library currently only supports `div` and `span`, for some reason, and if it doesn't find either of those in the `Wrapper` prop, it will fallback to `div`. I'm going to be forking and making this change, because I don't really see why it should work this way.

**Comment by aronhelser** [comment]
We would welcome a PR, if you would like to fix this behavior!

**Comment by danielbarion** [comment]
Guys, this solved for me: https://github.com/wwayne/react-tooltip/issues/587#issuecomment-619675399
