### ISSUE TITLE
[BUG] Tooltips aren't completely hidden on page when not showing

### ISSUE THREAD

**Issue by nina-johnson** [ReactTooltip/react-tooltip#918]
**Describe the bug**

Tooltips are not being fully hidden in the DOM

**Version of Package**
v5.4.0

**To Reproduce**

If you have a list of items (particularly one longer than the view-height of the page), tooltips will take up space in the background even if not active, causing the actual height of the page to be greater than necessary (on our app this caused a huge block of scrollable white space underneath our app).

On inspection, I noticed that tooltips have a CSS property of `visibility: hidden` rather than `display: none`, causing it to take up space (even if invisible).

**Expected behavior**

It should be using `display: none` when the tooltip is not showing to properly remove it from page calculations.

**Comment by gabrieljablonski** [comment]
This is definitely something we should look into. If I remember correctly, I've tried changing the `display` attribute instead of `visibility` but that led to some weird behavior when calculating the tooltip position.

There are even some other tooltip libraries that completely remove the tooltip element from the DOM when it isn't being shown, which might be the ideal way to do it.

We'll see what we can do to improve this, thanks for the report.

**Comment by nina-johnson** [comment]
Thank you for your quick response - yeah, agree about another way to do it is to only generate the tooltip when there's a "request" to display it. We added a work-around on our side but it's not as smooth as we'd like it to be.

**Comment by gabrieljablonski** [comment]
We're almost finished drafting up #932.

After some testing it seems like it will work fine. Any input is appreciated.
Either way, a new version should be up soon with a fix for this.
