### ISSUE TITLE
How to recalculate the position when content inside changed?

### ISSUE THREAD

**Issue by Fankasy** [ReactTooltip/react-tooltip#938]
I am working on some codes about clicking text to copy to clipboard, and I show _'click to copy'_ first and after clicked, change the text to _'copied to clipboard'_ , so I set a state for changing the text. After clicked, it did change the text but the arrow's position moved. How could I solve this issue? I thought it because the overridePosition function didn't be triggered. 

Here is pieces of my code:
```javascript
...
    <TextField
      data-tip
      data-for="tooltip"
      onClick={handleClick}
      onMouseLeave={handleFade}
    >
      {text}
    </TextField>
...
```
```javascript
...
      <StyledReactTooltip
        id="tooltip"
        place="top"
        border
        overridePosition={overridePosition}
        borderColor="blue"
        arrowColor="#111111"
        delayShow={1000}
        delayHide={10}
        effect="solid"
        getContent={() => <>{getText()}</>}
      />
...
```

**Comment by gabrieljablonski** [comment]
I can see you're using react-tooltip v4. We recommend updating to v5 and [following the docs](https://react-tooltip.com/docs/getting-started) to help you migrate to the new version.

I'm not exactly sure, but you might be able to fix this problem by doing

```tsx
useEffect(() => {
  ReactTooltip.rebuild();
}, [getText]);
```

Even if this works, we still recommend upgrading to v5, since you might run into more problems in the future, and it will be a lot easier to help if you're using v5.
