### ISSUE TITLE
[BUG] place="top" problem with will-change: transform 

### ISSUE THREAD

**Issue by anhdd-kuro** [ReactTooltip/react-tooltip#997]
**Describe the bug**
When the parent has the CSS property `will-change: transform`, even if place="top" and positionStrategy="fixed", the position is being calculated incorrectly and displayed at the bottom instead of the top. ( ~ place="bottom" )

_`place="right" , "left"` working fine_

**Version of Package**
newest

**Expected behavior**
The position of the tooltip element should be calculated to the top

**Comment by gabrieljablonski** [comment]
Please provide a [CodeSandbox](https://codesandbox.io/embed/react-new) demonstrating this issue.

**Comment by anhdd-kuro** [comment]
> Please provide a [CodeSandbox](https://codesandbox.io/embed/react-new) demonstrating this issue.
Here is the demo
https://codesandbox.io/s/jolly-smoke-jl4sdb?file=/src/App.js

**Comment by gabrieljablonski** [comment]
According to the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change), `will-change` should be used very sparingly and as a last resort, so the first suggestion is to consider if you really need it (you most likely don't).

As for an actual solution, I believe the issue happens because using `transform` on an element creates a new stacking context, so the tooltip is unable to "pop out" of it.

The easiest way to go around this is to move the tooltip outside of your `transform`ed element. Here's [your example](https://codesandbox.io/s/admiring-artem-gf3d8j?file=/src/App.js) with that change. This should not have any undesired side-effects.
